[package]
name = "secp256kfun"
version = "0.7.1"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
license = "0BSD"
homepage = "https://github.com/LLFourn/secp256kfun"
repository = "https://github.com/LLFourn/secp256kfun"
documentation = "https://docs.rs/secp256kfun"
description = "A mid-level secp256k1 library optimized for fun!"
edition = "2021"
rust-version = "1.60"
categories = ["cryptography", "cryptography::cryptocurrencies"]
readme = "README.md"
keywords = ["bitcoin", "secp256k1"]


[dependencies]
digest = "0.10"
subtle = { package = "subtle-ng", version = "2" }
rand_core = { version = "0.6" }

# optional
serde = { version = "1.0",  optional = true, default-features = false, features = ["derive"] }
secp256k1 = { version = "0.24", optional = true, default-features = false }
proptest = { version = "1", optional = true }

[dev-dependencies]
serde_json = "1"
rand = { version = "0.8" }
lazy_static = "1.4"
sha2 = "0.10"
proptest = "1"
secp256k1 = { version = "0.24", features = ["std", "global-context"]}

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
secp256k1 = { version = "0.24", default-features = false, features = ["std"] }
bincode = "1.0"
criterion = "0.3"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["std"]
alloc = ["serde?/alloc"]
std = ["alloc"]
libsecp_compat = ["secp256k1"]
serde = [ "dep:serde", "secp256k1?/serde" ]

[[bench]]
name = "bench_ecmult"
harness = false

[[bench]]
name = "bench_point"
harness = false


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
