name: Tests


on:
  push:
    branches:
      - master
  pull_request:

jobs:

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # We want to test stable on multiple platforms with --all-features
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        args: [ "--all-features" ]
        rust: [stable]
        target: ["x86_64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v2.0.0

      - name: cross test (armv7)
        uses: actions-rs/cargo@v1
        with:
          use-cross:  ${{ matrix.target != 'x86_64-unknown-linux-gnu' }}
          command: test
          args:  ${{ matrix.args }} --release --verbose --target ${{ matrix.target }}

  # test nightly build/test
  test-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: "x86_64-unknown-linux-gnu"
          override: true
      - uses: Swatinem/rust-cache@v2.0.0
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --verbose --all-features

  # test without default features
  test-minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: "x86_64-unknown-linux-gnu"
          override: true
      - uses: Swatinem/rust-cache@v2.0.0
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --verbose --no-default-features

  doc-build:
     name: doc-build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: nightly
           override: true
       - name: build-doc
         # convoluted way to make it fail on warnings
         run: "cargo doc --no-deps --workspace 2>&1 | tee /dev/fd/2 | grep -iEq '^(warning|error)' && exit 1 || exit 0"
